#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "superbin"
name = "SuperBin"
description.en = "Pastebin, File Sharing and URL Shortener with Password, Curl and QR support"
description.fr = "Pastebin, partage de fichiers et raccourcisseur d'URL avec prise en charge des mots de passe, Curl et QR"

version = "1.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/Th0rum/SuperBin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Th0rum/SuperBin/archive/refs/tags/1.0.0.tar.gz"
    sha256 = "02d758e3e823d340e2a7177072470cf9e29cbaf97c8c3210f5fdd090752a74db"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3001
